### ISSUE TITLE
Pressing enter doesn't execute the command.

### ISSUE THREAD

**Issue by Tikotik** [shsssc/cerebro-windows-shell#1]
Pressing enter doesn't execute the command and closes the cerebro to tray.

my cerebro version - 0.3.2

**Comment by shsssc** [comment]
I believe that's a bug in Cerebro.
Here's my fix:
https://github.com/KELiON/cerebro/pull/465/commits/f4a9f5514cc6b6665dbf26c28b7eb2522da9af28

If you want to fix this, please compile Cerebro with the patch above.
